name: Build and Release Switch ZIP

on:
  push:
    paths:
      - 'switch/**'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set timestamp
        id: timestamp
        run: |
          DATE=$(date +'%Y%m%d_%H%M')
          echo "DATE=$DATE" >> $GITHUB_ENV
          echo "TAG_NAME=$DATE" >> $GITHUB_ENV

      - name: Zip switch folder
        run: |
          zip -r lang.zip ./switch
          ls -lh lang.zip

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          name: ${{ env.DATE }}
          allowUpdates: true
          tag: ${{ env.TAG_NAME }}
          commit: main
          token: ${{ secrets.GITHUB_TOKEN }}
          body: "自動生成"
          artifacts: "lang.zip"

      - name: Remove old Releases
        uses: dev-drprasad/delete-older-releases@v0.3.2
        with:
          keep_latest: 1
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
